// init page
export const GET_ITEM_CART_REQUEST = 'GET_ITEM_CART_REQUEST';
export const GET_ITEM_CART_SUCCESS = 'GET_ITEM_CART_SUCCESS';
export const GET_ITEM_CART_FAILURE = 'GET_ITEM_CART_FAILURE';

// update quantity by productId
export const UPDATE_QUANTITY_CART_REQUEST = 'UPDATE_QUANTITY_CART_REQUEST';
export const UPDATE_QUANTITY_CART_SUCCESS = 'UPDATE_QUANTITY_CART_SUCCESS';
export const UPDATE_QUANTITY_CART_FAILURE = 'UPDATE_QUANTITY_CART_FAILURE';

// purchase 
export const PURCHASE_CART_REQUEST = 'PURCHASE_CART_REQUEST';
export const PURCHASE_CART_SUCCESS = 'PURCHASE_CART_SUCCESS';
export const PURCHASE_CART_FAILURE = 'PURCHASE_CART_FAILURE';