// init page
export const GET_ITEM_CART_REQUEST = 'GET_ITEM_CART_REQUEST';
export const GET_ITEM_CART_SUCCESS = 'GET_ITEM_CART_SUCCESS';
export const GET_ITEM_CART_FAILURE = 'GET_ITEM_CART_FAILURE';

//delete
export const REMOVE_ITEM_CART_REQUEST = 'REMOVE_ITEM_CART_REQUEST';
export const REMOVE_ITEM_CART_SUCCESS = 'REMOVE_ITEM_CART_SUCCESS';
export const REMOVE_ITEM_CART_FAILURE = 'REMOVE_ITEM_CART_FAILURT';

// update quantity by productId
export const UPDATE_QUANTITY_CART_REQUEST = 'UPDATE_QUANTITY_CART_REQUEST';
export const UPDATE_QUANTITY_CART_SUCCESS = 'UPDATE_QUANTITY_CART_SUCCESS';
export const UPDATE_QUANTITY_CART_FAILURE = 'UPDATE_QUANTITY_CART_FAILURE';

// purchase 
export const PURCHASE_CART_REQUEST = 'PURCHASE_CART_REQUEST';
export const PURCHASE_CART_SUCCESS = 'PURCHASE_CART_SUCCESS';
export const PURCHASE_CART_FAILURE = 'PURCHASE_CART_FAILURE';

// add to cart 
export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE';