
//get all
export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE';

//delete
export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAILURE = 'DELETE_CATEGORY_FAILURE';

//toggle
export const TOGGLE_CATEGORY_STATUS_REQUEST = 'TOGGLE_CATEGORY_STATUS_REQUEST';
export const TOGGLE_CATEGORY_STATUS_SUCCESS = 'TOGGLE_CATEGORY_STATUS_SUCCESS';
export const TOGGLE_CATEGORY_STATUS_FAILURE = 'TOGGLE_CATEGORY_STATUS_FAILURE';
