//render home
export const GET_HOME_ITEMS_REQUEST = 'GET_HOME_ITEMS_REQUEST';
export const GET_HOME_ITEMS_SUCCESS = 'GET_HOME_ITEMS_SUCCESS';
export const GET_HOME_ITEMS_FAILURE = 'GET_HOME_ITEMS_FAILURE';

//sort by price
export const GET_SORT_REQUEST = 'GET_SORT_REQUEST';
export const GET_SORT_SUCCESS = 'GET_SORT_SUCCESS';
export const GET_SORT_FAILURE = 'GET_SORT_FAILURE';

//get all categories
export const GET_LIST_CATEGORIES_REQUEST = 'GET_LIST_CATEGORIES_REQUEST';
export const GET_LIST_CATEGORIES_SUCCESS = 'GET_LIST_CATEGORIES_SUCCESS';
export const GET_LIST_CATEGORIES_FAILURE = 'GET_LIST_CATEGORIES_FAILURE';

//search product
export const SEARCH_PRODUCTS_REQUEST = 'SEARCH_PRODUCTS_REQUEST';
export const SEARCH_PRODUCTS_SUCCESS = 'SEARCH_PRODUCTS_SUCCESS';
export const SEARCH_PRODUCTS_FAILURE = 'SEARCH_PRODUCTS_FAILURE';