// init page
export const GET_ORDER_DETAIL_REQUEST = 'GET_ORDER_DETAIL_REQUEST';
export const GET_ORDER_DETAIL_SUCCESS = 'GET_ORDER_DETAIL_SUCCESS';
export const GET_ORDER_DETAIL_FAILURE = 'GET_ORDER_DETAIL_FAILURE';